name: Release Workflow
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  AUTH_SECRET: "secret"
  DEFAULT_PASSWORD: "any_pass"

on:
  push:
    branches:
      - master
      - develop

jobs:
  release:
    name: Generate Release notes, Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use nodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run Unit Tests
        id: unit-tests
        if: success()
        run: yarn test

      - name: Generate artifact of unit tests results
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-artifact
          path: |
            html-report
            !html-report/functional.html
            !html-report/jest-html-reporters-attach/functional

      - name: Check unit tests failures
        if: steps.unit-tests.outcome != 'success'
        run: exit 1

      - name: Generate new release
        id: semantic-release
        uses: codfish/semantic-release-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
